// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9v-59gdttpn8lU6a-rVPLkoJAmNW9HqI',
    appId: '1:331253331460:web:446160bf91c33b3c372751',
    messagingSenderId: '331253331460',
    projectId: 'place-comments-a6ee6',
    authDomain: 'place-comments-a6ee6.firebaseapp.com',
    storageBucket: 'place-comments-a6ee6.firebasestorage.app',
    measurementId: 'G-YHYMZZ8DBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7PGfzlSEDb0f2jYt4GfquQiO07JT5zw',
    appId: '1:331253331460:android:09b6359e63dccb9e372751',
    messagingSenderId: '331253331460',
    projectId: 'place-comments-a6ee6',
    storageBucket: 'place-comments-a6ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSP5DHQqpIb9DIx552joUqt0ihoiPzJWY',
    appId: '1:331253331460:ios:73c136b0a9fb2b10372751',
    messagingSenderId: '331253331460',
    projectId: 'place-comments-a6ee6',
    storageBucket: 'place-comments-a6ee6.firebasestorage.app',
    iosBundleId: 'com.example.kakaoMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSP5DHQqpIb9DIx552joUqt0ihoiPzJWY',
    appId: '1:331253331460:ios:73c136b0a9fb2b10372751',
    messagingSenderId: '331253331460',
    projectId: 'place-comments-a6ee6',
    storageBucket: 'place-comments-a6ee6.firebasestorage.app',
    iosBundleId: 'com.example.kakaoMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9v-59gdttpn8lU6a-rVPLkoJAmNW9HqI',
    appId: '1:331253331460:web:f04b25b5aa4f6398372751',
    messagingSenderId: '331253331460',
    projectId: 'place-comments-a6ee6',
    authDomain: 'place-comments-a6ee6.firebaseapp.com',
    storageBucket: 'place-comments-a6ee6.firebasestorage.app',
    measurementId: 'G-D8STYM88L2',
  );
}
